### ISSUE TITLE
[feature request] don’t consider URL in signatures

### ISSUE THREAD

**Issue by ploum** [forlater-email/navani#2]
If I’m correct, what is after a "--" in an email is considered as signature.
(it’s "-- \n", see https://en.wikipedia.org/wiki/Signature_block#Standard_delimiter )

It might be interesting to not consider URL in signatures. In my case, it would be useful but I don’t know if this could prevent other usecases.

**Comment by icyphox** [comment]
> If I’m correct, what is after a "--" in an email is considered as signature.␍
> (it’s "-- \n", see https://en.wikipedia.org/wiki/Signature_block#Standard_delimiter )␍
> ␍
> It might be interesting to not consider URL in signatures. In my case, it would be useful but I don’t know if this could prevent other usecases.␍

I'm actually already doing this (see:
https://github.com/forlater-email/navani/blob/b0009eb8c652bd24d944a649479a8a53ed8719d7/mail/utils.go#L21).
It's not the most robust, but it's enough for my use. Can you share what
your signature looks like? Maybe it's somehow slipping through...

--
Anirudh Oppiliappan
https://icyphox.sh

**Comment by ploum** [comment]
My bad! I had 3 "---" in my signature. Changing it to two solved my issue. Sorry for the noise and thanks again for your work :-)

**Comment by icyphox** [comment]
No worries!
